# Generated by Django 5.2.7 on 2025-10-09 04:04

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_productmodel_alter_productmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
