# Generated by Django 5.2.7 on 2025-10-17 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None, verbose_name='Теги'),
        ),
    ]
