# Generated by Django 5.2.7 on 2025-10-10 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phone',
            field=models.CharField(default=uuid.uuid4, max_length=11, unique=True, verbose_name='Телефон'),
        ),
    ]
